In [2]:
import pandas as pd

In [8]:
df=pd.read_csv(r"d:/major_ml/credit_card_fraud_detection/data/credit_data.csv")

In [10]:
df.describe(include="all")

,TransactionID,TransactionDate,Amount,MerchantID,TransactionType,Location,IsFraud
count,100000.000000,100000,100000.000000,100000.000000,100000,100000,100000.000000
unique,NaN,100000,NaN,NaN,2,10,NaN
top,NaN,2024-05-20 18:56:36.027551,NaN,NaN,refund,Chicago,NaN
freq,NaN,1,NaN,NaN,50131,10193,NaN
mean,50000.500000,NaN,2497.092666,501.676070,NaN,NaN,0.010000
std,28867.657797,NaN,1442.415999,288.715868,NaN,NaN,0.099499
min,1.000000,NaN,1.050000,1.000000,NaN,NaN,0.000000
25%,25000.750000,NaN,1247.955000,252.000000,NaN,NaN,0.000000
50%,50000.500000,NaN,2496.500000,503.000000,NaN,NaN,0.000000
75%,75000.250000,NaN,3743.592500,753.000000,NaN,NaN,0.000000
max,100000.000000,NaN,4999.770000,1000.000000,NaN,NaN,1.000000

In [11]:
df.head(1)

,TransactionID,TransactionDate,Amount,MerchantID,TransactionType,Location,IsFraud
0,1,2024-04-03 14:15:35.462794,4189.27,688,refund,San Antonio,0

In [12]:
df.dtypes

TransactionID        int64
TransactionDate     object
Amount             float64
MerchantID           int64
TransactionType     object
Location            object
IsFraud              int64
dtype: object